# Generated by Django 6.1.1 on 2026-09-30 15:07

import core.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Project Aplikasi', max_length=100)),
                ('description', models.TextField(default='Project Aplikasi')),
                ('version', models.CharField(default='1.0.0', max_length=20, validators=[core.utils.validators.validate_semver])),
                ('creator', models.CharField(default='Hamdayuwafii', max_length=255)),
                ('facebook', models.URLField(default='https://facebook.com/hamdayuwafii', max_length=500, validators=[core.utils.validators.validate_url_scheme])),
                ('instagram', models.URLField(default='https://instagram.com/hamdayuwafii', max_length=500, validators=[core.utils.validators.validate_url_scheme])),
                ('tiktok', models.URLField(default='https://www.tiktok.com/@hamdayuwafii', max_length=500, validators=[core.utils.validators.validate_url_scheme])),
                ('youtube', models.URLField(default='https://youtube.com/@hamdayuwafii', max_length=500, validators=[core.utils.validators.validate_url_scheme])),
                ('logo', models.ImageField(blank=True, max_length=500, null=True, upload_to='brand/logo/%Y/%m/', validators=[core.utils.validators.validate_image_extension, core.utils.validators.validate_image_size])),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Orgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.CharField(blank=True, default='', max_length=100)),
                ('logo', models.ImageField(blank=True, max_length=500, null=True, upload_to='orgs/logo/%Y/%m/', validators=[core.utils.validators.validate_image_extension, core.utils.validators.validate_image_size])),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('company_status', models.CharField(choices=[('pt', 'PT'), ('koperasi', 'Koperasi'), ('perum', 'Perum'), ('persero', 'Persero')], default='pt', max_length=50)),
                ('company_type', models.CharField(choices=[('konvensional', 'Konvensional'), ('syariah', 'Syariah')], default='konvensional', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('npwp', models.CharField(blank=True, max_length=30)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_date', models.DateField(blank=True, null=True)),
                ('deed_number', models.CharField(blank=True, max_length=100)),
                ('deed_date', models.DateField(blank=True, null=True)),
                ('last_amendment_number', models.CharField(blank=True, max_length=100)),
                ('last_amendment_date', models.DateField(blank=True, null=True)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('founded_place', models.CharField(blank=True, max_length=100)),
                ('business_sector', models.CharField(blank=True, max_length=100)),
                ('authorized_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('paid_up_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('business_scope', models.CharField(choices=[('kabupaten_kota', 'Kabupaten/Kota'), ('provinsi', 'Provinsi'), ('nasional', 'Nasional')], default='kabupaten_kota', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, default='Indonesia', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('fax', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True, max_length=500, validators=[core.utils.validators.validate_url_scheme])),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('products_services', models.TextField(blank=True)),
                ('total_branches', models.PositiveIntegerField(blank=True, null=True)),
                ('total_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('psp_name', models.CharField(blank=True, max_length=255)),
                ('psp_type', models.CharField(choices=[('badan_hukum', 'Badan Hukum'), ('perorangan', 'Perorangan')], default='badan_hukum', max_length=50)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Orgs',
                'verbose_name_plural': 'Orgs',
            },
        ),
    ]
