# Generated by Django 6.1.1 on 2026-10-02 08:39

import customer.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('nik', models.CharField(db_index=True, max_length=16, unique=True, validators=[customer.utils.validators.validate_nik])),
                ('customer_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customers/ktp/%Y/%m/', validators=[customer.utils.validators.validate_image_extension, customer.utils.validators.validate_image_size])),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='customers/selfie/%Y/%m/', validators=[customer.utils.validators.validate_image_extension, customer.utils.validators.validate_image_size])),
                ('gender', models.CharField(blank=True, choices=[('male', 'Laki-laki'), ('female', 'Perempuan')], db_index=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Belum Menikah'), ('married', 'Menikah'), ('divorced', 'Cerai'), ('widowed', 'Janda/Duda')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[customer.utils.validators.validate_phone_id])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('province', models.CharField(blank=True, db_index=True, max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, validators=[customer.utils.validators.validate_phone_id])),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
    ]
