# Generated by Django 6.1.1 on 2026-10-02 14:19

import customer.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nama Lengkap')),
                ('nik', models.CharField(db_index=True, help_text='16 angka sesuai KTP.', max_length=16, unique=True, validators=[customer.utils.validators.validate_nik], verbose_name='NIK')),
                ('customer_code', models.CharField(blank=True, db_index=True, help_text='Kosongkan agar dibuat otomatis.', max_length=20, null=True, unique=True, verbose_name='Kode Nasabah')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customers/ktp/%Y/%m/', validators=[customer.utils.validators.validate_image_extension, customer.utils.validators.validate_image_size], verbose_name='Foto KTP')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to='customers/selfie/%Y/%m/', validators=[customer.utils.validators.validate_image_extension, customer.utils.validators.validate_image_size], verbose_name='Foto Selfie')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Laki-laki'), ('female', 'Perempuan')], db_index=True, max_length=20, verbose_name='Jenis Kelamin')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Pekerjaan')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Belum Menikah'), ('married', 'Menikah'), ('divorced', 'Cerai'), ('widowed', 'Janda/Duda')], max_length=20, verbose_name='Status Pernikahan')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[customer.utils.validators.validate_phone_id], verbose_name='Nomor HP')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Kota')),
                ('province', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Provinsi')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Nama Kontak Darurat')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, validators=[customer.utils.validators.validate_phone_id], verbose_name='HP Kontak Darurat')),
                ('emergency_contact_relationship', models.CharField(blank=True, help_text='Contoh: Istri, Suami, Ayah, Ibu, Saudara.', max_length=50, verbose_name='Hubungan')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Nasabah',
                'verbose_name_plural': 'Nasabah',
                'ordering': ['name'],
            },
        ),
    ]
