# Generated by Django 6.1.1 on 2026-10-02 11:44

import django.core.validators
import django.db.models.deletion
import payment.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomor_pembayaran', models.CharField(blank=True, db_index=True, help_text='Kosongkan agar dibuat otomatis.', max_length=36, null=True, unique=True, validators=[payment.utils.validators.validate_payment_number], verbose_name='Nomor Pembayaran')),
                ('tanggal_bayar', models.DateField(db_index=True, verbose_name='Tanggal Bayar')),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jumlah Bayar')),
                ('tipe_pembayaran', models.CharField(choices=[('cicilan', 'Cicilan'), ('lunas', 'Lunas')], db_index=True, default='cicilan', max_length=20, verbose_name='Tipe Pembayaran')),
                ('metode_pembayaran', models.CharField(choices=[('cash', 'Tunai'), ('transfer', 'Transfer')], db_index=True, default='cash', max_length=20, verbose_name='Metode Pembayaran')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='transaction.transaction', verbose_name='Transaksi')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
                'ordering': ['-tanggal_bayar', '-created_at'],
            },
        ),
    ]
