# Generated by Django 6.1.1 on 2026-10-02 09:13

import collateral.utils.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='collaterals/photo/%Y/%m/', validators=[collateral.utils.validators.validate_image_extension, collateral.utils.validators.validate_image_size])),
                ('appraisal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('stored', 'Tersimpan'), ('redeemed', 'Ditebus'), ('auctioned', 'Dilelang')], db_index=True, default='stored', max_length=20)),
                ('intake_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaterals', to='vault.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaterals', to='customer.customer')),
                ('storages', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaterals', to='vault.storages')),
            ],
            options={
                'verbose_name': 'Collateral',
                'verbose_name_plural': 'Collaterals',
                'ordering': ['name'],
            },
        ),
    ]
