# Generated by Django 6.1.1 on 2026-10-02 11:16

import collateral.utils.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nama Barang')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Kosongkan agar dibuat otomatis.', max_length=20, null=True, unique=True, verbose_name='Kode Barang')),
                ('description', models.TextField(blank=True, verbose_name='Keterangan')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='collaterals/photo/%Y/%m/', validators=[collateral.utils.validators.validate_image_extension, collateral.utils.validators.validate_image_size], verbose_name='Foto Barang')),
                ('appraisal_value', models.DecimalField(blank=True, decimal_places=2, help_text='Nilai taksiran barang dalam Rupiah.', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000000)], verbose_name='Nilai Taksiran')),
                ('status', models.CharField(choices=[('stored', 'Tersimpan'), ('redeemed', 'Ditebus'), ('auctioned', 'Dilelang')], db_index=True, default='stored', max_length=20, verbose_name='Status')),
                ('intake_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Masuk')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaterals', to='vault.category', verbose_name='Kategori')),
                ('storages', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaterals', to='vault.storages', verbose_name='Gudang')),
            ],
            options={
                'verbose_name': 'Barang Jaminan',
                'verbose_name_plural': 'Barang Jaminan',
                'ordering': ['name'],
            },
        ),
    ]
