# Generated by Django 6.1.1 on 2026-10-02 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collateral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collateral',
            name='appraisal_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000000)]),
        ),
    ]
