# Generated by Django 6.1.1 on 2026-10-02 11:16

import django.core.validators
import django.db.models.deletion
import transaction.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collateral', '0001_initial'),
        ('customer', '0001_initial'),
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal_pinjam', models.DateField(db_index=True, verbose_name='Tanggal Pinjam')),
                ('tanggal_jatuh_tempo', models.DateField(db_index=True, help_text='Otomatis dihitung dari skema, bisa diubah manual.', verbose_name='Jatuh Tempo')),
                ('uang_pinjaman', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Uang Pinjaman')),
                ('tujuan_pinjaman', models.TextField(verbose_name='Tujuan Pinjam')),
                ('nomor_kontrak', models.CharField(blank=True, db_index=True, help_text='Kosongkan agar dibuat otomatis.', max_length=36, null=True, unique=True, validators=[transaction.utils.validators.validate_contract_number], verbose_name='Nomor Kontrak')),
                ('status_kontrak', models.CharField(choices=[('aktif', 'Aktif'), ('lunas', 'Lunas'), ('jatuh_tempo', 'Jatuh Tempo'), ('lelang', 'Lelang')], db_index=True, default='aktif', max_length=20, verbose_name='Status Kontrak')),
                ('collateral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='collateral.collateral', verbose_name='Barang Jaminan')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='customer.customer', verbose_name='Nasabah')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='vault.scheme', verbose_name='Skema')),
                ('storages', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='vault.storages', verbose_name='Gudang')),
            ],
            options={
                'verbose_name': 'Transaksi',
                'verbose_name_plural': 'Transaksi',
                'ordering': ['-tanggal_pinjam', '-created_at'],
            },
        ),
    ]
