# Generated by Django 6.1.1 on 2026-10-02 14:19

import django.core.validators
import vault.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Kode')),
                ('description', models.TextField(blank=True, verbose_name='Keterangan')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nama Skema')),
                ('bunga', models.DecimalField(decimal_places=2, help_text='Dalam persen, dihitung per periode.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Bunga (%)')),
                ('periode_bunga', models.IntegerField(choices=[(7, '7 Hari'), (15, '15 Hari'), (30, '30 Hari')], db_index=True, verbose_name='Periode Bunga')),
                ('durasi_maksimal_hari', models.PositiveIntegerField(help_text='Dalam hari.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durasi Maksimal')),
                ('denda_persen_perhari', models.DecimalField(decimal_places=2, help_text='Pilihan: 0.1, 0.2, 0.3, 0.4, 0.5.', max_digits=4, validators=[vault.utils.validators.validate_denda_persen], verbose_name='Denda (% per hari)')),
                ('biaya_admin', models.DecimalField(decimal_places=2, help_text='Dalam Rupiah.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Biaya Admin')),
            ],
            options={
                'verbose_name': 'Skema',
                'verbose_name_plural': 'Skema',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nama Gudang')),
                ('kode_gudang', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Kode Gudang')),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('penuh', 'Penuh'), ('rusak', 'Rusak')], db_index=True, default='tersedia', max_length=100, verbose_name='Status')),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Kota')),
                ('province', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Provinsi')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Kode Pos')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Nomor HP')),
                ('penanggung_jawab', models.CharField(blank=True, max_length=100, verbose_name='Petugas')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kapasitas')),
                ('current_occupancy', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Terisi')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('description', models.TextField(blank=True, verbose_name='Keterangan')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Gudang',
                'verbose_name_plural': 'Gudang',
                'ordering': ['name'],
            },
        ),
    ]
