# Generated by Django 6.1.1 on 2026-09-30 16:01

import django.core.validators
import vault.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('bunga', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('periode_bunga', models.IntegerField(choices=[(7, '7 Hari'), (15, '15 Hari'), (30, '30 Hari')], db_index=True)),
                ('durasi_maksimal_hari', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('denda_persen_perhari', models.DecimalField(decimal_places=2, max_digits=4, validators=[vault.utils.validators.validate_denda_persen])),
                ('biaya_admin', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Scheme',
                'verbose_name_plural': 'Schemes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('kode_gudang', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('penuh', 'Penuh'), ('rusak', 'Rusak')], db_index=True, default='tersedia', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('province', models.CharField(blank=True, db_index=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('penanggung_jawab', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('current_occupancy', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Storages',
                'verbose_name_plural': 'Storages',
                'ordering': ['name'],
            },
        ),
    ]
