# Generated by Django 6.1.1 on 2026-09-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_category_options_remove_category_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
    ]
