from django.db import models

from account.utils.constants import MANAGER_ROLES


class PeriodeBungaChoices(models.IntegerChoices):
    HARI_7 = 7, "7 Hari"
    HARI_15 = 15, "15 Hari"
    HARI_30 = 30, "30 Hari"


class StorageStatusChoices(models.TextChoices):
    TERSEDIA = "tersedia", "Tersedia"
    PENUH = "penuh", "Penuh"
    RUSAK = "rusak", "Rusak"


MAX_LENGTH_NAME = 100
MAX_LENGTH_CODE = 20
MAX_LENGTH_PHONE = 30
MAX_LENGTH_POSTAL_CODE = 10

DENDA_PERSEN_VALUES = (0.1, 0.2, 0.3, 0.4, 0.5)

BUNGA_MAX_DIGITS = 5
BUNGA_DECIMAL_PLACES = 2
BUNGA_MAX_VALUE = 100

DENDA_MAX_DIGITS = 4
DENDA_DECIMAL_PLACES = 2

BIAYA_ADMIN_MAX_DIGITS = 12
BIAYA_ADMIN_DECIMAL_PLACES = 2

LATITUDE_MAX_DIGITS = 9
LATITUDE_DECIMAL_PLACES = 6
LONGITUDE_MAX_DIGITS = 9
LONGITUDE_DECIMAL_PLACES = 6

DURASI_MIN_VALUE = 1

DEFAULT_IS_ACTIVE = True
DEFAULT_OCCUPANCY = 0

CATEGORIES_PER_PAGE = 10
SCHEMES_PER_PAGE = 10
STORAGES_PER_PAGE = 10
